repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.14.11
  hooks:
    - id: ruff-check
      args: ["src/", "scripts/", "test/", "--fix"]
      types_or: [ python, pyi ]
    - id: ruff-format
      args: ["src/", "scripts/", "test/"]
      types_or: [ python, pyi ]

- repo: local
  hooks:
    - id: ty
      name: ty check
      entry: uv run ty check src/ scripts/
      language: system
      types_or: [ python, pyi ]
